EmployeeManagement/Models/EmpSalaryModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeManagement.Models
{
    [Table("EmployeeSalary")]
    public class EmpSalaryModel
    {
        public int Id { get; set; }
        [Required]
        public DateTime YearMonth { get; set; }
        [Required]
        public double Salary { get; set; }

        public int EmployeeId { get; set; }
        public EmployeeModel Employee { get; set; }

    }
}

EmployeeManagement/Models/EmployeeModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeManagement.Models
{
    [Table("Employee")]
    public class EmployeeModel
    {
        public int Id { get; set; } 
        [Required]
        [MaxLength(40)]
        public string? FirstName { get; set; }
        [Required]
        [MaxLength(40)]
        public string? LastName { get; set; }
        [EmailAddress]
        public string? Email { get; set; }
        public string? Mobile { get; set; }
        public string? Address { get; set; }
        [Required]
        public DateTime DOB { get; set; }
        public string? Gender { get; set; }
        public string? Designation { get; set; }
        public DateTime? DOJ { get; set; }

    }
    public enum Gender
    {
        Male,
        Female,
        Other
    }

}

EmployeeManagement/Models/ErrorViewModel.cs
namespace EmployeeManagement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeeManagement/Models/Response.cs
namespace EmployeeManagement.Models
{
    public class Response
    {
        public int Status { get; set; }
        public string Message { get; set; }
    }
}

EmployeeManagement/Controllers/EmployeeController.cs
using EmployeeManagement.Data;
using EmployeeManagement.Models;
using EmployeeManagement.Repository;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _empRepo;
        private readonly ApplicationDbContext _context;
        public EmployeeController(IEmployeeRepository empRepo,ApplicationDbContext dbContext)
        {
            _empRepo = empRepo;
            _context = dbContext;
        }
        public IActionResult Index(int id = 0)
        {
            if(id == 0)
            {
                return View();
            }
            var employee = _context.employeeModels.Where(a  => a.Id == id).FirstOrDefault();
            return View(employee);
        }

        public IActionResult GetEmployees()
        {
            var empList = _empRepo.GetAllEmployees();
            return View(empList);
        }

        [HttpPost]
        public IActionResult SaveEmployee(EmployeeModel employeeData)
        {
            var response = _empRepo.AddOrUpdateEmployee(employeeData);
            if (response.Status == 1)
            {
                return Json(response);
            }
            else
            {
                return Json(response);
            }
        }


        [HttpPost]
        public IActionResult DeleteEmployee(int id)
        {
            var response = _empRepo.DeleteEmployee(id);
            return RedirectToAction("GetEmployees");
        }


    }
}

EmployeeManagement/Controllers/HomeController.cs
using EmployeeManagement.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployeeManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeManagement/Controllers/SalaryController.cs
using EmployeeManagement.Data;
using EmployeeManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Controllers
{
    public class SalaryController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public SalaryController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            List<EmpSalaryModel> empSalary = _dbContext.empSalaryModels.Include(e => e.Employee).ToList();
            return View(empSalary);
        }
    }
}

EmployeeManagement/Views/Employee/GetEmployees.cshtml
@model List<EmployeeModel>
@{
    Layout = "/Views/_employee.cshtml";
}

<div class="text-center" style="border-bottom:1px solid darkgray">
    <div style="display:flex;justify-content:space-between">
        <h5 style="margin:0 1rem">Employee List</h5>
        <div style="text-align:right;margin-right:1%">
            <input id="inputSearch" placeholder="search" style="border-radius:5px;border:1px solid grey;" />
        </div>
    </div>
    <div style="overflow-x:scroll;overflow-y:scroll;" class="mt-3">
        <table style="width:1200px;height:400px;" class="table table-bordered">
            <thead style="background-color:gainsboro">
                <tr>
                    <td>Id</td>
                    <td>Empoyee Name</td>
                    <td>DOJ</td>
                    <td>Designation</td>
                    <td>Email</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.FirstName @item.LastName</td>
                        <td>@item.DOJ</td>
                        <td>@item.Designation</td>
                        <td>@item.Email</td>
                        <td>
                            <a href="@Url.Action("Index", "Employee", new { id = item.Id })" class="btn btn-primary">Edit</a>
                            <form action="@Url.Action("DeleteEmployee", "Employee", new { id = item.Id })" method="post" style="display:inline;">
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this employee?');">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

EmployeeManagement/Views/Employee/Index.cshtml
@model EmployeeModel
@{
    Layout = "/Views/_employee.cshtml";
}
<div class="row">
    <h3>Add Employee</h3>
    <form id="employeeForm" asp-action="SaveEmployee" asp-controller="Employee" method="post" enctype="multipart/form-data">

        <div class="row mt-4 form-group">
            <div class="col form-floating">
                <input id="EmpId" type="hidden" asp-for="Id" />
                <input id="inputFirstName" type="text" asp-for="FirstName" class="form-control" placeholder="First Name" aria-label="First Name" />
                <label for="inputFirstName" class="form-label">First Name</label>
            </div>
            <div class="col form-floating">
                <input id="inputLastName" type="text" asp-for="LastName" class="form-control" placeholder="Last Name" aria-label="Last Name" />
                <label for="inputLastName" class="form-label">Last Name</label>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col form-floating">
                <input id="inputDOB" type="date" asp-for="DOB" class="form-control" placeholder="DOB" aria-label="Date of Birth" onchange="check(this)" />
                <label for="inputDOB" class="form-label">DOB</label>
            </div>
            <div class="col form-floating">
                <select id="inputGender" asp-for="Gender" class="form-control">
                    <option value=""> -- Select --</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                </select>
                <label for="inputGender" class="form-label">Gender</label>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col form-floating">
                <input id="inputEmail" type="text" asp-for="Email" class="form-control" placeholder="Email" aria-label="Email" />
                <label for="inputEmail" class="form-label">Email</label>
            </div>
            <div class="col form-floating">
                <input id="inputMobile" type="text" asp-for="Mobile" class="form-control" placeholder="Mobile Number" aria-label="Mobile Number" />
                <label for="inputMobile" class="form-label">Mobile Number</label>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col form-floating">
                <input id="inputDesignation" type="text" asp-for="Designation" class="form-control" placeholder="Designation" aria-label="Designation" />
                <label for="inputDesignation" class="form-label">Designation</label>
            </div>
            <div class="col form-floating">
                <input id="inputDOJ" type="date" asp-for="DOJ" class="form-control" placeholder="Date of joining" aria-label="DOJ" />
                <label for="inputDOJ">DOJ</label>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col form-floating">
                <input id="inputAddress" type="text" asp-for="Address" class="form-control" placeholder="Address" aria-label="Address" />
                <label for="inputAddress">Address</label>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col" style="text-align:center;">
                <button @* onclick="AddEmployee()" *@ type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
@* <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script> *@
<script>
    $(document).ready(function () {
        // $(".datepicker").datepicker({
        //     format: 'dd-mm-yyyy',
        //     autoclose: true,
        //     orientation: "bottom auto"
        // });

        $("#employeeForm").submit(function (event) {
            event.preventDefault();
        });
    });

    function check() {
        debugger;
        var dob = new Date($("#inputDOB").val());
        var now = new Date();
        var age = now.getFullYear() - dob.getFullYear();
        var monthDiff = now.getMonth() - dob.getMonth();

        if (monthDiff < 0 || (monthDiff === 0 && now.getDate() < dob.getDate())) {
            age--;
        }

        if (age < 18 || age > 60) {
            alert('Age must be between 18 and 60 years.');
            $("#inputDOB").val('');
        }
    }

    $("#employeeForm").submit(function (event) {
        event.preventDefault();

        var regex = /^[a-zA-Z]+$/;
        var emailPattern = /^[a-zA-Z0-9._%+-]+@@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;

        var firstName = $("#inputFirstName").val();
        var lastName = $("#inputLastName").val();
        var email = $("#inputEmail").val();
        var Mobile = $("#inputMobile").val();
        var Address = $("#inputAddress").val();
        var DOB = $("#inputDOB").val();
        var Gender = $("#inputGender").val();
        var Designation = $("#inputDesignation").val();
        var DOJ = $("#inputDOJ").val();

        if (!firstName) {
            alert("Please enter first name");
            $("#inputFirstName").focus();
            return;
        }
        else if (!regex.test(firstName)) {
            alert("No special character allowed");
            $("#inputFirstName").focus();
            return;
        }

        if (!lastName) {
            alert("Please enter last name");
            $("#inputLastName").focus();
            return;
        }
        else if (!regex.test(lastName)) {
            alert("No special character allowed");
            $("#inputLastName").focus();
            return;
        }

        if (!email) {
            alert("Please enter Email")
            return;
        }
        else if (!emailPattern.test(email)) {
            alert("Please enter correct Email")
            return;
        }

        var employeeData = {

            Id: $("#EmpId").val(),
            FirstName: firstName,
            LastName: lastName,
            Email: email,
            Mobile: Mobile,
            Address: Address,
            DOB: DOB,
            Gender: Gender,
            Designation: Designation,
            DOJ: DOJ
        }; 

        var formAction = $(this).attr("action");

        $.ajax({
            method: 'POST',
            url: formAction,
            data: employeeData ,
            success: function (response) {
                alert("Saved successfully: " + response.message);
                $("#employeeForm")[0].reset();
            },
            error: function (xhr, status, error) {
                alert("Error: " + xhr.responseText);
            }
        });

    });


</script>

EmployeeManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EmployeeManagement/Views/Salary/Index.cshtml
@model List<EmpSalaryModel>
@{
}


<div class="text-center mt-4" style="border-bottom:1px solid darkgray">
    <div style="display:flex;justify-content:space-between">
        <div>
            <button class="btn btn-success" id="addButton" data-toggle="modal" data-target="#salaryModal">Add</button>
        </div>
        <div>
            <input id="inputSearch" placeholder="search" style="border-radius:5px;border:1px solid grey;" />
        </div>
    </div>
    <div style="overflow-x:scroll;overflow-y:scroll;" class="mt-3">
        <table style="width:1200px;height:400px;" class="table table-bordered">
            <thead style="background-color:gainsboro">
                <tr>
                    <td>Empoyee Name</td>
                    <td>Month-Year</td>
                    <td>Salary</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Employee.FirstName @item.Employee.LastName
                        </td>
                        <td>@item.YearMonth</td>
                        <td>@item.Salary</td>
                        <td>
                            <a href="@Url.Action("Index", "Salary", new { id = item.Id })" class="btn btn-primary">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

<script>

</script>

EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Management</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet">

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Employee Management</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="/Employee/Index">
                            Home
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Salary/Index">Salary</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/Privacy">Currency Convert</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    

</body>
</html>
@await RenderSectionAsync("Scripts", required: false)

EmployeeManagement/Views/_employee.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
<div>
    <div>
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a href="/Employee/GetEmployees" class="nav-link">Employee List</a>
                    </li>
                    <li class="nav-item">
                        <a href="/Employee/Index" class="nav-link">Add Employee</a>
                    </li>
                </ul>
            </div>
            <div class="card-body">
                <div>
                    <div>
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>